server:
  port: 8088
spring:
  application:
    name: agences
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:1234/apache_camel
    username: postgres
    password: 1111
    hikari:
      maximum-pool-size: 20
  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect